/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package table;

/**
 *
 * @author Win10
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jFood = new javax.swing.JLabel();
        jDrinks = new javax.swing.JLabel();
        jDessert = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jB3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jB4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFood.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jFood.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Downloads\\menu-removebg-preview.png")); // NOI18N
        jFood.setText("FOODS");
        jFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFoodMouseClicked(evt);
            }
        });
        jPanel6.add(jFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 196, 118, -1));

        jDrinks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jDrinks.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Downloads\\drinks-removebg-preview.png")); // NOI18N
        jDrinks.setText("DRINKS");
        jDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDrinksMouseClicked(evt);
            }
        });
        jPanel6.add(jDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 280, 118, 46));

        jDessert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jDessert.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Downloads\\dessertss-removebg-preview.png")); // NOI18N
        jDessert.setText("DESSERT");
        jDessert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDessertMouseClicked(evt);
            }
        });
        jPanel6.add(jDessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 367, 118, 46));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Pictures\\ARSMOS__1_-removebg-preview.png")); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 120));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 153));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 230));

        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 230, 230));

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 230, 230));

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, 230));

        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 230, 230));

        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 230, 230));

        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 230, 230));

        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 230, 230));

        jPanel38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 230, 230));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBackground(new java.awt.Color(255, 153, 153));
        jPanel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 230));

        jPanel50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 230, 230));

        jPanel51.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 230, 230));

        jPanel52.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, 230));

        jPanel53.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 230, 230));

        jPanel54.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 230, 230));

        jPanel55.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 230, 230));

        jPanel56.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 230, 230));

        jPanel57.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 230, 230));

        jPanel4.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 840));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel18.setBackground(new java.awt.Color(255, 153, 153));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 230));

        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 230, 230));

        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 230, 230));

        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, 230));

        jPanel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 230, 230));

        jPanel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 230, 230));

        jPanel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 230, 230));

        jPanel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 230, 230));

        jPanel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 255), 5, true));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel18.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 230, 230));

        jTabbedPane1.addTab("tab2", jPanel18);

        jPanel28.setBackground(new java.awt.Color(255, 153, 153));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", jPanel28);

        jPanel29.setBackground(new java.awt.Color(255, 153, 153));
        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", jPanel29);

        jPanel30.setBackground(new java.awt.Color(255, 153, 153));
        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 6));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab2", jPanel30);

        jPanel6.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 6, 920, 880));

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 3, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CLICK THE ICON TO ORDER: CLICK THE ICON TO ORDER: CLICK THE ICON TO ORDER: CLICK THE ICON TO ORDER: CLICK THE ICON TO ORDER:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 920, 20));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 920, 40));

        jB3.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jB3.setText("CASH");
        jB3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        jPanel6.add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 130, 40));

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setText("MODE OF PAYMENT:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 180, 40));

        jB4.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jB4.setText("E-PAY");
        jB4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        jPanel6.add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 130, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFoodMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jFoodMouseClicked

    private void jDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDrinksMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jDrinksMouseClicked

    private void jDessertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDessertMouseClicked
       jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jDessertMouseClicked

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
       
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JLabel jDessert;
    private javax.swing.JLabel jDrinks;
    private javax.swing.JLabel jFood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
